on: [push, pull_request]

name: CI

jobs:
  shellcheck:
    name: Run shellcheck
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - run: find dev -name '*.sh' | xargs docker run -v $(pwd):/mnt koalaman/shellcheck:v0.7.1
